openapi: 3.0.1
info:
  title: ShopApi
  version: "1.0"
servers:
- url: /
security:
- Bearer: []
paths:
  /api/Login/Login:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginModel'
          text/json:
            schema:
              $ref: '#/components/schemas/LoginModel'
          application/*+json:
            schema:
              $ref: '#/components/schemas/LoginModel'
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
          description: OK
      tags:
      - Login
  /api/Login/Refresh:
    post:
      parameters:
      - explode: true
        in: query
        name: SSAID
        required: false
        schema:
          type: string
        style: form
      requestBody:
        content:
          application/json:
            schema:
              type: string
          text/json:
            schema:
              type: string
          application/*+json:
            schema:
              type: string
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
          description: OK
      tags:
      - Login
  /api/Login/Register:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterModel'
          text/json:
            schema:
              $ref: '#/components/schemas/RegisterModel'
          application/*+json:
            schema:
              $ref: '#/components/schemas/RegisterModel'
      responses:
        "200":
          description: OK
      tags:
      - Login
  /api/Login/Logout:
    post:
      responses:
        "200":
          description: OK
      tags:
      - Login
  /api/Product/InitProductFromCSV:
    post:
      responses:
        "200":
          description: OK
      tags:
      - Product
  /api/Product/TestApiDirectly:
    get:
      responses:
        "200":
          description: OK
      tags:
      - Product
  /api/Product/GetProductFromOpenFoodFacts:
    get:
      parameters:
      - explode: true
        in: query
        name: barcode
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Product'
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
            text/json:
              schema:
                $ref: '#/components/schemas/Product'
          description: OK
      tags:
      - Product
  /api/Product/GetProductByBarcode:
    get:
      parameters:
      - explode: true
        in: query
        name: barcode
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            text/plain:
              schema:
                items:
                  $ref: '#/components/schemas/Product'
                type: array
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Product'
                type: array
            text/json:
              schema:
                items:
                  $ref: '#/components/schemas/Product'
                type: array
          description: OK
      tags:
      - Product
  /api/Product/AddProduct:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
          text/json:
            schema:
              $ref: '#/components/schemas/Product'
          application/*+json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        "200":
          description: OK
      tags:
      - Product
  /api/Product/GetAllProducts:
    get:
      responses:
        "200":
          description: OK
      tags:
      - Product
  /api/Product/GetAllProductsTestOpenApiGenerate:
    get:
      responses:
        "200":
          description: OK
      tags:
      - Product
  /api/User/GetUser:
    get:
      parameters:
      - explode: true
        in: query
        name: idUser
        required: false
        schema:
          format: int32
          type: integer
        style: form
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/UserInfo'
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfo'
            text/json:
              schema:
                $ref: '#/components/schemas/UserInfo'
          description: OK
      tags:
      - User
components:
  schemas:
    Barcode:
      additionalProperties: false
      example:
        product: null
        code: code
        productId: 5
        id: 5
      properties:
        id:
          format: int32
          type: integer
        code:
          nullable: true
          type: string
        productId:
          format: int32
          type: integer
        product:
          $ref: '#/components/schemas/Product'
      type: object
    ELoginType:
      enum:
      - Mobile
      - Web
      - External
      type: string
    InventoryPosition:
      additionalProperties: false
      example:
        product: null
        quantity: 7.061401241503109
        productId: 3
        price: 9.301444243932576
        inventoryDate: 2000-01-23T04:56:07.000+00:00
        id: 2
        userId: 2
        user:
          createdAt: 2000-01-23T04:56:07.000+00:00
          surname: surname
          roleForUsers:
          - userRoleId: 1
            userRole:
              code: code
              roleForUsers:
              - null
              - null
              name: name
              id: 1
            userId: 7
            user: null
          - userRoleId: 1
            userRole:
              code: code
              roleForUsers:
              - null
              - null
              name: name
              id: 1
            userId: 7
            user: null
          name: name
          id: 4
          passowrd: passowrd
          email: email
          username: username
          updatedAt: 2000-01-23T04:56:07.000+00:00
      properties:
        id:
          format: int32
          type: integer
        quantity:
          format: double
          type: number
        price:
          format: double
          type: number
        inventoryDate:
          format: date-time
          type: string
        productId:
          format: int32
          type: integer
        userId:
          format: int32
          type: integer
        product:
          $ref: '#/components/schemas/Product'
        user:
          $ref: '#/components/schemas/User'
      type: object
    LoginModel:
      additionalProperties: false
      example:
        password: password
        loginType: null
        ssaid: ssaid
        username: username
      properties:
        username:
          minLength: 1
          type: string
        password:
          minLength: 1
          type: string
        ssaid:
          nullable: true
          type: string
        loginType:
          $ref: '#/components/schemas/ELoginType'
      required:
      - password
      - username
      type: object
    Product:
      additionalProperties: false
      example:
        unit:
          code: code
          name: name
          id: 1
          products:
          - null
          - null
        isGeneral: true
        name: name
        unitId: 6
        id: 0
        label: label
        barcodes:
        - product: null
          code: code
          productId: 5
          id: 5
        - product: null
          code: code
          productId: 5
          id: 5
        brand: brand
        inventoryPositions:
        - product: null
          quantity: 7.061401241503109
          productId: 3
          price: 9.301444243932576
          inventoryDate: 2000-01-23T04:56:07.000+00:00
          id: 2
          userId: 2
          user:
            createdAt: 2000-01-23T04:56:07.000+00:00
            surname: surname
            roleForUsers:
            - userRoleId: 1
              userRole:
                code: code
                roleForUsers:
                - null
                - null
                name: name
                id: 1
              userId: 7
              user: null
            - userRoleId: 1
              userRole:
                code: code
                roleForUsers:
                - null
                - null
                name: name
                id: 1
              userId: 7
              user: null
            name: name
            id: 4
            passowrd: passowrd
            email: email
            username: username
            updatedAt: 2000-01-23T04:56:07.000+00:00
        - product: null
          quantity: 7.061401241503109
          productId: 3
          price: 9.301444243932576
          inventoryDate: 2000-01-23T04:56:07.000+00:00
          id: 2
          userId: 2
          user:
            createdAt: 2000-01-23T04:56:07.000+00:00
            surname: surname
            roleForUsers:
            - userRoleId: 1
              userRole:
                code: code
                roleForUsers:
                - null
                - null
                name: name
                id: 1
              userId: 7
              user: null
            - userRoleId: 1
              userRole:
                code: code
                roleForUsers:
                - null
                - null
                name: name
                id: 1
              userId: 7
              user: null
            name: name
            id: 4
            passowrd: passowrd
            email: email
            username: username
            updatedAt: 2000-01-23T04:56:07.000+00:00
        capacity: capacity
      properties:
        id:
          format: int32
          type: integer
        name:
          nullable: true
          type: string
        brand:
          nullable: true
          type: string
        capacity:
          nullable: true
          type: string
        label:
          nullable: true
          type: string
        isGeneral:
          type: boolean
        unitId:
          format: int32
          type: integer
        unit:
          $ref: '#/components/schemas/Unit'
        barcodes:
          items:
            $ref: '#/components/schemas/Barcode'
          nullable: true
          type: array
        inventoryPositions:
          items:
            $ref: '#/components/schemas/InventoryPosition'
          nullable: true
          type: array
      type: object
    RegisterModel:
      additionalProperties: false
      example:
        password: password
        surname: surname
        name: name
        confirmPassword: confirmPassword
        email: email
        username: username
      properties:
        name:
          maxLength: 50
          minLength: 0
          type: string
        surname:
          maxLength: 50
          minLength: 0
          type: string
        username:
          maxLength: 50
          minLength: 3
          type: string
        email:
          format: email
          minLength: 1
          type: string
        password:
          maxLength: 100
          minLength: 6
          type: string
        confirmPassword:
          minLength: 1
          type: string
      required:
      - confirmPassword
      - email
      - name
      - password
      - surname
      - username
      type: object
    RoleForUser:
      additionalProperties: false
      example:
        userRoleId: 1
        userRole:
          code: code
          roleForUsers:
          - null
          - null
          name: name
          id: 1
        userId: 7
        user: null
      properties:
        userId:
          format: int32
          type: integer
        userRoleId:
          format: int32
          type: integer
        user:
          $ref: '#/components/schemas/User'
        userRole:
          $ref: '#/components/schemas/UserRole'
      type: object
    Unit:
      additionalProperties: false
      example:
        code: code
        name: name
        id: 1
        products:
        - null
        - null
      properties:
        id:
          format: int32
          type: integer
        name:
          nullable: true
          type: string
        code:
          nullable: true
          type: string
        products:
          items:
            $ref: '#/components/schemas/Product'
          nullable: true
          type: array
      type: object
    User:
      additionalProperties: false
      example:
        createdAt: 2000-01-23T04:56:07.000+00:00
        surname: surname
        roleForUsers:
        - userRoleId: 1
          userRole:
            code: code
            roleForUsers:
            - null
            - null
            name: name
            id: 1
          userId: 7
          user: null
        - userRoleId: 1
          userRole:
            code: code
            roleForUsers:
            - null
            - null
            name: name
            id: 1
          userId: 7
          user: null
        name: name
        id: 4
        passowrd: passowrd
        email: email
        username: username
        updatedAt: 2000-01-23T04:56:07.000+00:00
      properties:
        id:
          format: int32
          type: integer
        name:
          nullable: true
          type: string
        surname:
          nullable: true
          type: string
        username:
          nullable: true
          type: string
        email:
          nullable: true
          type: string
        passowrd:
          nullable: true
          type: string
        createdAt:
          format: date-time
          type: string
        updatedAt:
          format: date-time
          nullable: true
          type: string
        roleForUsers:
          items:
            $ref: '#/components/schemas/RoleForUser'
          nullable: true
          type: array
      type: object
    UserInfo:
      additionalProperties: false
      example:
        surname: surname
        roles:
        - roles
        - roles
        name: name
        id: 0
        email: email
        username: username
      properties:
        id:
          format: int32
          type: integer
        name:
          nullable: true
          type: string
        surname:
          nullable: true
          type: string
        username:
          nullable: true
          type: string
        email:
          nullable: true
          type: string
        roles:
          items:
            type: string
          nullable: true
          type: array
      type: object
    UserRole:
      additionalProperties: false
      example:
        code: code
        roleForUsers:
        - null
        - null
        name: name
        id: 1
      properties:
        id:
          format: int32
          type: integer
        code:
          nullable: true
          type: string
        name:
          nullable: true
          type: string
        roleForUsers:
          items:
            $ref: '#/components/schemas/RoleForUser'
          nullable: true
          type: array
      type: object
  securitySchemes:
    Bearer:
      description: "JWT Authorization header using the Bearer scheme. Example: \"\
        Authorization: Bearer {token}\""
      in: header
      name: Authorization
      type: apiKey

